factions:
   NameMinCharacters: 3
   NameMaxCharacters: 16
   maxMembers: 25
   maxClaims: 8
   maxAllies: 1
   dtr:
    RegenFreezeBaseMinutes: 40
    minutesPerMember: 2
    minimum: -50
    maximum: 6.0
    millisecondsBetweenUpdates: 45000
    incrementBetweenUpdates: 0.1
   relationColours:
      warzone: "LIGHT_PURPLE"
      wilderness: "DARK_GREEN" 
      teammate: "GREEN"
      ally: "GOLD"
      enemy: "RED"
      road: "YELLOW"
      safezone: "AQUA"
   antirotation:
      delay: 6
      enabled: false
   endportal:
      enabled: true
      center: 1000
      radius: 7
   spawn:
      radiusOverworld: 800  
      radiusNether: 800
   roads:
     widthLeft: 7
     widthRight: 7
     length: 4000
     allowClaimsBesides: true
   warzone:
     radiusOverworld: 800
     radiusNether: 800
   disallowednames:
     - "ETB"
   home:
     teleportdelay:
        normal: 10
        nether: 20
        end: 30
        allowTeleportingInEnemyTerritory: true
        maxHeight: -1
subclaimsigns:
     private: false
     Captain: false
     leader: false
     hoppercheck: false
preventAllyAttackDamage: true
messageDebug: false  
mongo:
  use: true
  host: "n1-c2-mongodb-clevercloud-customers.services.clever-cloud.com:27017,n2-c2-mongodb-clevercloud-customers.services.clever-cloud.com:27017"
  database: "bz5tv19wwqmhwvd"
  username: "uyiynvbaeurstqdxiuv3"
  password: "rmpqalpSJnlVDhf0LfLW"
  replicaSet: "rs0"     
